export const chatMessages = [
    { id: 1, userName: "vinothini", message: "New version available! Refresh to update." },
    { id: 2, userName: "john", message: "Hey, how are you doing today?" },
    { id: 3, userName: "emma", message: "I just finished the report you asked for." },
    { id: 4, userName: "system", message: "Your password has been successfully changed." },
    { id: 5, userName: "mike", message: "Are we still meeting at 3 PM?" },
    { id: 6, userName: "bot", message: "Need help? Type 'support' to chat with a representative." },
    { id: 7, userName: "alice", message: "Congratulations on your promotion!" },
    { id: 8, userName: "david", message: "Let’s catch up over coffee sometime." },
    { id: 9, userName: "system", message: "Your account has been locked due to suspicious activity." },
    { id: 10, userName: "nina", message: "Can you send me the file by end of the day?" },
    { id: 11, userName: "bot", message: "Hi there! How can I assist you today?" },
    { id: 12, userName: "luke", message: "I’m running late, but I’ll be there soon." },
    { id: 13, userName: "system", message: "Your session will expire in 5 minutes. Please save your work." },
    { id: 14, userName: "ella", message: "Thank you for your help earlier!" },
    { id: 15, userName: "bot", message: "Here are the top search results for your query." },
    { id: 16, userName: "henry", message: "Did you watch the game last night?" },
    { id: 17, userName: "system", message: "A scheduled update will occur at 2 AM tonight." },
    { id: 18, userName: "ava", message: "I loved your latest blog post!" },
    { id: 19, userName: "bot", message: "Searching for nearby restaurants..." },
    { id: 20, userName: "oliver", message: "Let’s plan a trip this weekend!" },
    { id: 21, userName: "system", message: "Upload failed. File size exceeds the limit." },
    { id: 22, userName: "mia", message: "Don’t forget about our meeting tomorrow." },
    { id: 23, userName: "jack", message: "Happy birthday! Have an amazing day!" },
    { id: 24, userName: "bot", message: "Tip: Use strong passwords to keep your account secure." },
    { id: 25, userName: "lily", message: "Your presentation was fantastic!" },
    { id: 26, userName: "system", message: "Connection lost. Trying to reconnect..." },
    { id: 27, userName: "sophie", message: "Do you want to join us for dinner tonight?" },
    { id: 28, userName: "bot", message: "Your current balance is $123.45." },
    { id: 29, userName: "ryan", message: "Can you review the document I sent?" },
    { id: 30, userName: "system", message: "Payment failed. Please verify your card details." },
    { id: 31, userName: "grace", message: "The client loved your idea!" },
    { id: 32, userName: "bot", message: "Hi! I can assist you with booking tickets." },
    { id: 33, userName: "leo", message: "Check out this cool video I found!" },
    { id: 34, userName: "system", message: "Unauthorized access. Please log in again." },
    { id: 35, userName: "ruby", message: "What time is the meeting scheduled for?" },
    { id: 36, userName: "bot", message: "I didn’t understand that. Could you rephrase?" },
    { id: 37, userName: "zara", message: "I need your feedback on this design." },
    { id: 38, userName: "system", message: "Your account settings have been updated." },
    { id: 39, userName: "bot", message: "You’ve been logged out due to inactivity." },
    { id: 40, userName: "max", message: "Can you share the link with me?" },
    { id: 41, userName: "system", message: "Your subscription has been successfully renewed." },
    { id: 42, userName: "diana", message: "That was an amazing concert last night!" },
    { id: 43, userName: "bot", message: "Did you mean 'schedule'?" },
    { id: 44, userName: "sam", message: "Can you call me when you’re free?" },
    { id: 45, userName: "system", message: "Your profile picture has been updated." },
    { id: 46, userName: "ella", message: "Let’s meet at the park later." },
    { id: 47, userName: "bot", message: "Here’s a joke: Why don’t skeletons fight each other? They don’t have the guts!" },
    { id: 48, userName: "james", message: "Do you need any help with the project?" },
    { id: 49, userName: "system", message: "Your order has been shipped." },
    { id: 50, userName: "lucy", message: "I’m so proud of what you’ve accomplished!" },
    { id: 51, userName: "system", message: "New device detected. Was this you?" },
    { id: 52, userName: "bot", message: "Fun fact: Honey never spoils!" },
    { id: 53, userName: "willow", message: "I loved the movie we watched together." },
    { id: 54, userName: "system", message: "Password reset link sent to your email." },
    { id: 55, userName: "mason", message: "Can you check your messages?" },
    
  ];

//    const chatMessages = [
//     {
//       id: 1,
//       img: "https://i.pravatar.cc/150?img=1",
//       userName: "vinothini",
//       message: "New version available! Refresh to update.",
//     },
//     {
//       id: 2,
//       img: "https://i.pravatar.cc/150?img=2",
//       userName: "john",
//       message: "Hey, how are you doing today?",
//     },
//     {
//       id: 3,
//       img: "https://i.pravatar.cc/150?img=3",
//       userName: "emma",
//       message: "I just finished the report you asked for.",
//     },
//     {
//       id: 4,
//       img: "https://i.pravatar.cc/150?img=4",
//       userName: "mike",
//       message: "Are we still meeting at 3 PM?",
//     },
//     {
//       id: 5,
//       img: "https://i.pravatar.cc/150?img=5",
//       userName: "nina",
//       message: "Can you send me the file by the end of the day?",
//     },
//     {
//       id: 6,
//       img: "https://i.pravatar.cc/150?img=6",
//       userName: "david",
//       message: "Let’s catch up over coffee sometime.",
//     },
//     {
//       id: 7,
//       img: "https://i.pravatar.cc/150?img=7",
//       userName: "alice",
//       message: "Congratulations on your promotion!",
//     },
//     {
//       id: 8,
//       img: "https://i.pravatar.cc/150?img=8",
//       userName: "ryan",
//       message: "Can you review the document I sent?",
//     },
//     {
//       id: 9,
//       img: "https://i.pravatar.cc/150?img=9"
//     }]
  
  